openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
  description: Documentation for Todo API
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /todos:
    get:
      summary: Get all todos
      responses:
        '200':
          description: Returns all todos
        '500':
          description: Server error
    post:
      summary: Add a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Created
        '400':
          description: Bad request
        '500':
          description: Server error
  /todos/{id}:
    put:
      summary: Update a todo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Updated
        '404':
          description: Not found
        '500':
          description: Server error
    delete:
      summary: Delete a todo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No content
        '500':
          description: Server error